site_name: OTOBO and Znuny Python SDKs
site_description: Documentation for the OTOBO and Znuny GenericInterface Python SDKs.
repo_url: https://github.com/Softoft-GmbH/otobo-znuny-python-client
repo_name: Softoft-GmbH/otobo-znuny-python-client
nav:
  - Home: index.md
  - OTOBO Getting Started: getting-started-otobo.md
  - Znuny Getting Started: getting-started-znuny.md
  - Migration: migration.md
  - Interactive Installation Setup: interactive-installation-setup.md
  - Library Overview: library-overview.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - toc.integrate
  language: en
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
plugins:
  - search
edit_uri: edit/main/docs/
docs_dir: docs
