from otobo.models.ticket_models import DynamicFieldItem, ArticleDetail

Ticket = [TicketDetail(TicketID=12, TicketNumber='2024100201000065',
        Title='ticket - <OTOBO_TICKET_DynamicField_customerUserIHKAbteilung_Value>',
        State='closed successful', StateType='closed', StateID=2, Priority='4 high', PriorityID=4,
        Queue='Postmaster', QueueID=1, Lock='unlock', LockID=1, Owner='root@localhost', OwnerID=1,
        Responsible='root@localhost', ResponsibleID=1, CustomerID='GreenIT', CustomerUserID='bernd.helm',
        SLAID='', ServiceID='', Type='Unclassified', TypeID=1, ArchiveFlag='n', Age=22770730,
        EscalationResponseTime=0, EscalationUpdateTime=0, EscalationSolutionTime=0, EscalationTime=0,
        CreateBy=1, ChangeBy=2, Created='2024-10-02 07:02:39', Changed='2024-10-02 07:05:39', Article=[
            ArticleDetail(CommunicationChannel=None, CommunicationChannelID=3, IsVisibleForCustomer=1, SenderTypeID='3',
                AutoResponseType=None, From='"bernd helm" <bernd.helm@softoft.de>', Subject='TEST',
                Body='\n6\n\n', ContentType='text/plain; charset=utf-8', MimeType='text/plain', Charset='utf-8',
                CreateTime='2024-10-02 07:02:39', ChangeTime='2024-10-02 07:02:39', IncomingTime=1727852559,
                To='Postmaster', SenderType='customer', IsEdited=0, Cc='', Bcc='', ReplyTo='', InReplyTo='',
                References='', MessageID='', ContentCharset='utf-8', ChangeBy=1, CreateBy=1, IsDeleted=0,
                ArticleID=18, ArticleNumber=2),
            ArticleDetail(CommunicationChannel=None, CommunicationChannelID=3, IsVisibleForCustomer=1, SenderTypeID='1',
                AutoResponseType=None, From='GenericAgent', Subject='[Ticket#2024100201000065] ticket -',
                Body='ticket - ', ContentType='text/plain; charset=utf-8', MimeType='text/plain', Charset='utf-8',
                CreateTime='2024-10-02 07:02:39', ChangeTime='2024-10-02 07:02:39', IncomingTime=1727852559,
                To='', SenderType='agent', IsEdited=0, Cc='', Bcc='', ReplyTo='', InReplyTo='', References='',
                MessageID='', ContentCharset='utf-8', ChangeBy=1, CreateBy=1, IsDeleted=0, ArticleID=19,
                ArticleNumber=1)], DynamicField=[DynamicFieldItem(Name='Equipment', Value=None),
            DynamicFieldItem(Name='ITSMCriticality', Value=None),
            DynamicFieldItem(Name='ITSMImpact', Value=None),
            DynamicFieldItem(Name='PreProcAccommodationDatesFrom',
                Value=None),
            DynamicFieldItem(Name='PreProcAccommodationDatesTo', Value=None),
            DynamicFieldItem(Name='PreProcAccomodationTotalCosts',
                Value=None),
            DynamicFieldItem(Name='PreProcExpenseReceiptsRequired',
                Value=None),
            DynamicFieldItem(Name='PreProcFlightClass', Value=None),
            DynamicFieldItem(Name='PreProcFlightDepartureLocationFromTo',
                Value=None),
            DynamicFieldItem(Name='PreProcFlightReturnLocationFromTo',
                Value=None),
            DynamicFieldItem(Name='PreProcFlightStopoverLocation',
                Value=None),
            DynamicFieldItem(Name='PreProcFlightTotalCosts', Value=None),
            DynamicFieldItem(Name='PreProcLocalDepartureLocationFromTo',
                Value=None),
            DynamicFieldItem(Name='PreProcLocalReturnLocationFromTo',
                Value=None),
            DynamicFieldItem(Name='PreProcLocalTotalCosts', Value=None),
            DynamicFieldItem(Name='PreProcLocalTravelReimbursementPerKm',
                Value=None),
            DynamicFieldItem(Name='PreProcTravelApprovalYesNo', Value=None),
            DynamicFieldItem(Name='PreProcTravelExpensesInformationComplete',
                Value=None),
            DynamicFieldItem(Name='PreProcTravelExpensesProcessState',
                Value=None),
            DynamicFieldItem(Name='PreProcTravelPerDiem', Value=None),
            DynamicFieldItem(Name='ProcessManagementActivityID', Value=None),
            DynamicFieldItem(Name='ProcessManagementProcessID', Value=None),
            DynamicFieldItem(Name='customerUserIHKAbteilung', Value=None)])]
