name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12","3.13"]
        mode: ["latest","min"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
      - run: uv tool install tox --with tox-uv --with tox-min-req
      - run: tox -e py${{ matrix.python-version//. }}-${{ matrix.mode }}
